version: "3.9"

services:

  web:
    build: .
    container_name: springboot-web

    ports:
      - "8081:8080"
      - "81:80"
      - "2222:22"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SOKHOM_Panha-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123

  mysql:
    image: mysql:8

    container_name: mysql-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: SOKHOM_Panha-db

    ports:
      - "3307:3306"